server:
  port: 8081
spring: 
  #Redis配置
  redis:
    database: 0
    password: bitbuy-redis
    sentinel:
      master: mymaster
      nodes: 192.168.9.232:26379,192.168.9.232:26380,192.168.9.232:26381
